- name: Converge agent host
  hosts: agent-host
  roles:
    - role: "{{ playbook_dir|dirname|dirname }}"
      vars:
        hids_host_role: agent
        hids_agent_name: test
        hids_manager: manager-host
